// src/admin/pages/home/layout.vue
<script setup>
import Preview from "./components/preview.vue";
</script>

<template>
    <div>
        <div class="mt-20">
            <div class="w-full flex justify-center">
                <div class="h-[70vh] bg-white shadow-lg border border-gray-200 rounded-2xl overflow-hidden flex">
                    <Preview />
                    <router-view class="p-8 max-w-96 re-scroll flex flex-col" />
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: "HomeLayout",
}
</script>

// src/admin/layout/index.tsx
import { ReactNode } from "react";

export default function AdminLayout({ children }: { children: ReactNode }) {
    return (
        <div className="mt-20 w-full flex justify-center">
            <div
                className="h-[70vh] bg-white shadow-lg border border-gray-200 rounded-3xl overflow-hidden flex">
                {children}
            </div>
        </div>
    )
}
