// src/frontend/components/preview.vue
<template>
  <div class="w-80 rounded-2xl overflow-hidden min-h-[70vh]">
    <canvas id="canvas" ref="canvas" width="100%" height="100%" />
  </div>
</template>

<script>
import { defineComponent, ref } from "vue";

export default defineComponent({
  name: "Preview",
  props: {
    bank: String,
    acc_name: String,
    acc_num: String,
    acc_bank_short: String,
    image: String,
  },

  data(){
    return {
      bg: "",
      qr: "",
      context: "",
    }
  },

  setup() {
    const canvas = ref();
    return { canvas };
  },

  mounted() {
    this.init();
  },

  methods: {
    init() {
      if (this.canvas) {
        const rect = canvas.parentNode.getBoundingClientRect();
        this.context = this.canvas.getContext("2d");
        this.context.imageSmoothingEnabled = false;
        this.canvas.width = rect.width;
        this.canvas.height = rect.height;
        this.bg = new Image();
        this.qr = new Image();
        this.bg.src = window.WPLKPathx.assets + this.image;
        this.qr.src = `https://img.vietqr.io/image/${this.bank}-${this.num}-qr_only.png`;

        this.bg.onload = () => {
          this.draw();
        };

        this.qr.onload = () => {
          this.draw();
        };
      }
    },

    draw() {
      this.drawImage();
      this.drawQR();
      this.drawText();
    },

    drawImage() {
      this.context.drawImage(
        this.bg,
        0,
        0,
        this.canvas.width,
        this.canvas.height
      );
    },

    drawQR() {
      this.context.drawImage(this.qr, 10, 10, 110, 110);
    },

    drawText() {
      this.context.font = "bold 36px Lato";
      this.context.fillStyle = "#FFFFFF";
      this.context.fillText(this.acc_name, 20, this.canvas.height - 100);
      this.context.font = "bold 21px Lato";
      this.context.fillText(this.acc_bank_short, 20, this.canvas.height - 70);
      this.context.font = "bold 21px Lato";
      this.context.fillText(this.acc_num, 20, this.canvas.height - 50);
    },
  },
});
</script>

// src/admin/pages/home/components/preview.tsx
import { BankQRContext, BankQRContextType } from "src/store/bankQR";
import { useContext, useEffect, useRef, useState } from "react";

export default function Preview() {
  const [qr, setQr] = useState(new Image());
  const [bg, setBg] = useState(new Image());
  const { state } = useContext(BankQRContext) as BankQRContextType;
  const [size, setSize] = useState<{ width: number, height: number }>({ width: 0, height: 0 });
  const [context, setContext] = useState<CanvasRenderingContext2D | null>(null);
  const canvas = useRef<HTMLCanvasElement>(null);

  function draw() {
    drawImage();
    drawQR();
    drawText();
  };

  function drawImage() {
    context && context.drawImage(
      bg, 0, 0,
      size.width,
      size.height
    );
  }

  function drawQR() {
    context && context.drawImage(
      qr, 10, 10, 110, 110
    );
  }

  function drawText() {
    if (context) {
      context.font = "bold 36px Lato";
      context.fillStyle = "#FFFFFF";
      context.fillText(state.account.name, 20, size.height - 100);
      context.font = "bold 21px Lato";
      context.fillText(state.account.bank, 20, size.height - 70);
      context.font = "bold 21px Lato";
      context.fillText(state.account.number, 20, size.height - 50);
    }
  }

  useEffect(() => {
    if (canvas.current) {
      const parentNode = canvas.current.parentNode as HTMLElement;
      if (parentNode) {
        const rect = parentNode.getBoundingClientRect();

        setSize({ width: rect.width, height: rect.height });
        setContext(canvas.current.getContext("2d"));
        if (context) {
          context.imageSmoothingEnabled = false;

        }
      }
    }

    bg.onload = () => draw();
    qr.onload = () => draw();

  }, [])

  useEffect(() => {
    draw();
  }, [state.account.bank_short, state.account.name])

  useEffect(() => {
    qr.src = `https://img.vietqr.io/image/${state.account.bank}-${state.account.number}-qr_only.png`;
    draw();
  }, [state.account.bank, state.account.number])

  useEffect(() => {
    bg.src = window.WPSFPath.assets + state.image;
    draw();
  }, [state.image])

  return (
    <div className="w-80 flex-none rounded-2xl overflow-hidden shadow-xl h-full">
      <canvas id="canvas" ref={canvas} width="100%" height="100%" />
    </div>
  )
}
