// src/admin/pages/home/components/setting1.tsx
import Header from "./header";
import Form from "./form";
import Select from "@admin/components/select"
import Input from "@admin/components/input"
import Button from "@admin/components/button";

import { IoMdArrowForward } from "react-icons/io"

import { BankAccount, BankQRContextType } from "@admin/store/bankQR";
import { useNavigate } from "react-router-dom";
import { useContext, useEffect, useState } from "react";
import { BankQRContext } from "@admin/store/bankQR";
import { BankData, getBankBins } from "../utils";

export default function Setting1() {
  const navigate = useNavigate();
  const { state, changeAcc } = useContext(BankQRContext) as BankQRContextType;
  const [bankList, setBankList] = useState<BankData[]>([]);

  useEffect(() => {
    getBankBins().then((data) => {
      setBankList(data);
    })
  }, [])

  function handleNext(data: BankAccount) {
    console.log(data);
    navigate("/create/step2");
  }

  function handleBank(data: string) {
    changeAcc({
      name: state.account.name,
      number: state.account.number,
      bank: data,
      bank_short:
        bankList.filter((item) => item.bin === data)[0].shortName,
    })
  }

  function handleAccNumber(data: string) {
    changeAcc({
      name: state.account.name,
      number: data,
      bank: state.account.bank,
      bank_short: state.account.bank_short,
    })
  }

  function handleAccName(data: string) {
    changeAcc({
      name: data,
      number: state.account.number,
      bank: state.account.bank,
      bank_short: state.account.bank_short,
    });
  }

  return (
    <div>
      <Header
        title="Thông tin tài khoản"
        subtitle="Tạo mã QR kèm lời chúc cho những người thân yêu"
      />

      <div className="pt-8 h-full">
        <Form
          onSubmit={handleNext}
          input_component={
            <div>
              <Select
                title="Ngân hàng"
                id="bank"
                placeholder="Chọn một ngân hàng"
                data={bankList.map(bank => ({ name: bank.bin, value: bank.name }))}
                value={state.account.bank}
                onChange={handleBank}
              />
              <Input
                title="Số tài khoản"
                type="number"
                id="number"
                placeholder="0123456789"
                required
                value={state.account.number}
                onChange={handleAccNumber}
              />
              <Input
                title="Chủ sở hữu"
                type="text"
                id="acc_name"
                placeholder="Trịnh Văn Mớt"
                required
                value={state.account.name}
                onChange={handleAccName}
              />
            </div>
          }

          button_element={
            <div>
              <Button title="Tiếp tục" icon={<IoMdArrowForward />} type="submit" />
            </div>
          }
        >
        </Form>
      </div>
    </div>
  )
}

// src/admin/pages/home/components/Setting1.vue
<template>
  <div>
    <Header
      title="Thông tin tài khoản"
      subtitle="Tạo mã QR kèm lời chúc cho những người thân yêu"
    />

    <div class="pt-8 h-full">
      <Form @next="handleNext">
        <template v-slot:input_area>
          <Select
            title="Ngân hàng"
            id="bank"
            placeholder="Chọn một ngân hàng"
            :data="banks"
            :defaultValue="bank"
            @update:model-value="handleBank"
          />
          <Input
            title="Số tài khoản"
            type="number"
            id="acc_number"
            placeholder="0123456789"
            required
            :defaultValue="acc_number"
            @update:model-value="handleAccNumber"
          />
          <Input
            title="Chủ sở hữu"
            type="text"
            id="acc_name"
            placeholder="Trịnh Văn Mớt"
            required
            :defaultValue="acc_name"
            @update:model-value="handleAccName"
          />
        </template>

        <template v-slot:button_area>
          <Button title="Tiếp tục" icon submit>
            <template v-slot:icon>
              <RightIcon />
            </template>
          </Button>
        </template>
      </Form>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import Input from "@admin/components/input.vue";
import Select from "@admin/components/select.vue";
import Button from "@admin/components/button.vue";
import Header from "./header.vue";
import Form from "./form.vue";
import RightIcon from "vue-ionicons/dist/ios-arrow-forward.vue";

import { getBankBins } from "../utils";
import { IAccount } from "@/admin/store/state";
import { MutationTypes } from "@admin/store/mutation";

export default defineComponent({
  name: "Setting1",
  components: {
    Input,
    Select,
    Button,
    Header,
    RightIcon,
    Form,
  },
  data() {
    return {
      banks: [],
    };
  },
  mounted() {
    this.fetchData();
  },
  computed: {
    acc_number() {
      return this.$store.state.account.acc_number;
    },
    acc_name() {
      return this.$store.state.account.acc_name;
    },
    bank() {
      return this.$store.state.account.bank;
    },
  },
  methods: {
    fetchData() {
      getBankBins().then((data) => {
        // @ts-ignore
        this.banks = data;
      });
    },

    handleAccNumber(data: string) {
      this.acc_number = data;

      this.$store.commit(MutationTypes.UPDATE_ACCOUNT, {
        bank: this.bank,
        acc_name: this.acc_name,
        acc_number: data,
        bank_short: this.$store.state.account.bank_short,
      });
    },

    handleAccName(data: string) {
      this.acc_name = data;
      this.$store.commit(MutationTypes.UPDATE_ACCOUNT, {
        bank: this.bank,
        acc_name: data,
        acc_number: this.acc_number,
        bank_short: this.$store.state.account.bank_short,
      });
    },

    handleBank(data: string) {
      this.bank = data;

      this.$store.commit(MutationTypes.UPDATE_ACCOUNT, {
        bank: data,
        acc_name: this.acc_name,
        acc_number: this.acc_number,
        // @ts-ignore
        bank_short:
          // @ts-ignore
          this.banks.filter((item) => item.bin === data)[0].shortName,
      });
    },

    handleNext(data: IAccount) {
      console.log(data);
      this.$store.commit(MutationTypes.UPDATE_ACCOUNT, data);
      this.$router.push("/create/step2");
    },
  },
});
</script>
