// src/admin/pages/home/components/setting2.tsx
import { useNavigate } from "react-router-dom"
import Form from "./form"
import Header from "./header"
import Input from "@admin/components/input"
import { useContext, useEffect, useState } from "react"
import { BankQRContext, BankQRContextType } from "@admin/store/bankQR"
import SelectImage from "@admin/components/select_image"
import Button from "@admin/components/button"
import { IoMdArrowForward, IoMdArrowBack } from "react-icons/io"

export default function Setting2() {
  const navigate = useNavigate();
  const { state, changeWish, changeImage } = useContext(BankQRContext) as BankQRContextType;
  const [imageList, setImageList] = useState<{ name: string, value: string }[]>([]);

  function handleNext(data: any) {
    console.log(data);
    navigate("/create/step3");
  }

  function handleWish(data: string) {
    console.log(data);
    changeWish(data);
  }

  function handleImage(data: string) {
    console.log(data);
    changeImage(data);
  }

  function backStep() {
    navigate("/create");
  }

  useEffect(() => {
    setImageList([
      { value: "images/preview.png", name: "1" },
      { value: "images/preview_2.png", name: "2" },
      { value: "images/preview_3.png", name: "3" },
      { value: "images/preview_4.png", name: "4" },
    ])
  })

  return (
    <div>
      <Header
        title="Phong bao"
        subtitle="Tạo mã QR kèm lời chúc cho những người thân yêu"
      />

      <div className="pt-8 h-full">
        <Form
          onSubmit={handleNext}
          input_component={
            <div>
              <Input
                title="Lời chúc"
                type="text"
                id="wish"
                placeholder="Chúc mừng bạn"
                required
                value={state.wish}
                onChange={handleWish}
              />

              <SelectImage
                onChange={handleImage}
                data={imageList}
                value={state.image}
                title="Chọn mẫu"
                id="image"
              />
            </div>
          }

          button_element={
            <div>
              <Button onClick={backStep} styleBtn="Alternative" icon_center={<IoMdArrowBack />} />
              <Button title="Tiếp tục" icon={<IoMdArrowForward />} type="submit" />
            </div>
          }>
        </Form>
      </div>
    </div>
  )
}

// src/admin/pages/home/components/Setting2.vue
<template>
  <div>
    <Header
      title="Phong bao"
      subtitle="Tạo mã QR kèm lời chúc cho những người thân yêu"
    />

    <div class="pt-8 h-full">
      <Form @next="handleNext">
        <template v-slot:input_area>
          <Input
            title="Lời chúc"
            type="text"
            id="wish"
            placeholder="Chúc mừng bạn"
            required
            :defaultValue="wish"
            @update:model-value="handleWish"
          />
          <SelectImage
            @update:model-value="handleImage"
            :data="images"
            :defaultValue="image"
          />
        </template>

        <template v-slot:button_area>
          <Button @onClick="backStep" type="Alternative" icon_center>
            <template v-slot:icon_center>
              <LeftIcon />
            </template>
          </Button>
          <Button title="Tiếp tục" icon submit>
            <template v-slot:icon>
              <RightIcon />
            </template>
          </Button>
        </template>
      </Form>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import Input from "@admin/components/input.vue";
import Button from "@admin/components/button.vue";
import SelectImage from "@admin/components/select_image.vue";
import RightIcon from "vue-ionicons/dist/ios-arrow-forward.vue";
import LeftIcon from "vue-ionicons/dist/ios-arrow-back.vue";
import Form from "./form.vue";
import Header from "./header.vue";

import { MutationTypes } from "@admin/store/mutation";

export default defineComponent({
  name: "Setting2",
  components: {
    Input,
    SelectImage,
    Button,
    RightIcon,
    LeftIcon,
    Form,
    Header,
  },

  computed: {
    wish() {
      return this.$store.state.wish;
    },
    image() {
      return this.$store.state.image;
    },
  },

  setup() {
    return {
      images: [
        { url: "images/preview.png" }, 
        { url: "images/preview_2.png" },
        { url: "images/preview_3.png" },
        { url: "images/preview_4.png" },
      ],
    };
  },
  methods: {
    backStep() {
      this.$router.push("/create");
    },

    handleWish(data) {
      console.log(data);

      this.wish = data;
      this.$store.commit(MutationTypes.UPDATE_WISH, data);
    },

    handleImage(data) {
      console.log(data);

      this.image = data;
      this.$store.commit(MutationTypes.UPDATE_IMAGE, data);
    },

    handleNext(data: any) {
      console.log(data);
      this.$store.commit(MutationTypes.UPDATE_WISH, data.wish);
      this.$router.push("/create/step3");
    },
  },
});
</script>
