// src/admin/pages/message/components/setting3.tsx
import { MessageApi } from "@admin/apis";
import Button from "@admin/components/button";
import Form from "@admin/components/form";
import Header from "@admin/components/header";
import Input from "@admin/components/input";
import { MessageContext, MessageContextType } from "@admin/store/message";
import { useContext } from "react";
import { IoMdArrowBack, IoMdArrowForward } from "react-icons/io";
import { useNavigate } from "react-router-dom";

export default function Setting3() {
    const navigate = useNavigate();
    const { state, changePassword, changeLink } = useContext(MessageContext) as MessageContextType;

    async function handleNext() {
        console.log(state);
        const link = await MessageApi.add(state);
        if (link) {
            changeLink(link);
            navigate("/message/create/step4");
        }
    }

    function handleBack() {
        navigate("/message/create/step2");
    }

    function handlePassword(data: string) {
        changePassword(data);
    }

    return (
        <>
            <Header
                title="Chọn chủ đề"
                subtitle="Chọn một chủ đề bắt mắt"
            />

            <Form
                onSubmit={handleNext}
                input_component={
                    <>
                        <Input
                            title="Mật khẩu"
                            type="password"
                            id="password"
                            placeholder="****"
                            required
                            value={state.password}
                            onChange={handlePassword}
                        />
                    </>
                }

                button_element={
                    <>
                        <Button onClick={handleBack} styleBtn="Alternative" icon_center={<IoMdArrowBack />} />
                        <Button title="Tạo thôi" icon={<IoMdArrowForward />} type="submit" />
                    </>
                }
            >
            </Form>
        </>
    )
}

// src/admin/pages/home/components/Setting3.vue
<template>
  <div>
    <Header
      title="Mật khẩu"
      subtitle="Tạo mã QR kèm lời chúc cho những người thân yêu"
    />

    <div class="pt-8 h-full">
      <Form @next="handleNext">
        <template v-slot:input_area>
          <Input
            title="Mật khẩu"
            type="password"
            id="password"
            placeholder="*****"
            required
            :defaultValue="password"
          />
        </template>

        <template v-slot:button_area>
          <Button @onClick="backStep" type="Alternative" icon_center>
            <template v-slot:icon_center>
              <LeftIcon />
            </template>
          </Button>
          <Button title="Tạo thôi" icon submit>
            <template v-slot:icon>
              <RightIcon />
            </template>
          </Button>
        </template>
      </Form>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import Input from "@admin/components/input.vue";
import Button from "@admin/components/button.vue";
import RightIcon from "vue-ionicons/dist/ios-arrow-forward.vue";
import LeftIcon from "vue-ionicons/dist/ios-arrow-back.vue";
import Header from "./header.vue";
import Form from "./form.vue";

import { MutationTypes } from "@admin/store/mutation";

export default defineComponent({
  name: "Setting3",
  components: {
    Input,
    Button,
    RightIcon,
    LeftIcon,
    Header,
    Form,
  },
  computed: {
    password() {
      return this.$store.state.password;
    },
  },
  methods: {
    backStep() {
      this.$router.push("/create/step2");
    },
    handleNext(data: any) {
      console.log(data);
      this.$store.commit(MutationTypes.UPDATE_PASSWORD, data.password);
      this.$router.push("/create/step4");
    },
  },
});
</script>
