// src/admin/pages/home/layout.tsx
import { Outlet } from "react-router-dom";
import Preview from "./components/preview";

export default function HomeLayout() {
  return (
    <div>
      <div className="mt-20">
        <div className="w-full flex justify-center">
          <div
            className="h-[70vh] bg-white shadow-lg border border-gray-200 rounded-3xl overflow-hidden flex"
          >
            <div className="p-2 flex justify-center items-center">
              <Preview />
            </div>
            <div className="p-8 pl-10 max-w-96 re-scroll flex flex-col">
              <Outlet />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// src/admin/pages/home/layout.vue
<script setup>
import Preview from "./components/preview.vue";
</script>

<template>
    <div>
        <div class="mt-20">
            <div class="w-full flex justify-center">
                <div class="h-[70vh] bg-white shadow-lg border border-gray-200 rounded-3xl overflow-hidden flex">
                    <div class="p-2 ps-5 flex justify-center items-center">
                        <Preview />
                    </div>
                    <router-view class="p-8 pl-10 max-w-96 re-scroll flex flex-col" />
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: "HomeLayout",
}
</script>
