// src/admin/pages/home/components/Setting4.vue
<template>
  <div>
    <Header
      title="Xong rùi!"
      subtitle="Tạo mã QR kèm lời chúc cho những người thân yêu"
    />

    <div class="pt-8 h-full">
      <Form @next="handleNext">
        <template v-slot:input_area>
          <div class="flex items-end gap-2">
            <Input
              title="Link của bạn đây"
              type="text"
              id="link"
              :defaultValue="link"
              disabled
            />

            <div class="mb-5 flex gap-2">
              <Button @onClick="open" icon_center type="Alternative">
                <template v-slot:icon_center>
                  <OpenIcon />
                </template>
              </Button>
              <Button @onClick="copy" icon_center>
                <template v-slot:icon_center>
                  <CopyIcon />
                </template>
              </Button>
            </div>
          </div>
        </template>

        <template v-slot:button_area>
          <Button title="Hoàn thành" @onClick="handleNext" icon>
            <template v-slot:icon>
              <CheckIcon />
            </template>
          </Button>
        </template>
      </Form>
    </div>
  </div>
</template>

<script>
import Input from "@admin/components/input.vue";
import Button from "@admin/components/button.vue";
import Header from "./header.vue";
import Form from "./form.vue";

import CheckIcon from "vue-ionicons/dist/ios-happy.vue";
import CopyIcon from "vue-ionicons/dist/ios-copy.vue";
import OpenIcon from "vue-ionicons/dist/ios-open.vue";

export default {
  name: "Setting3",
  components: {
    Input,
    Button,
    CheckIcon,
    CopyIcon,
    OpenIcon,
    Header,
    Form,
  },
  computed: {
    link() {
      return this.$store.state.link;
    },
  },
  methods: {
    copy() {
      window.navigator.clipboard.writeText(this.$store.state.link);
    },
    open() {
      window.open(this.$store.state.link);
    },
    handleNext() {
      this.$router.push("/create");
    },
  },
};
</script>

// src/admin/pages/message/components/setting4.tsx
import { useNavigate } from "react-router-dom"
import Form from "@admin/components/form"
import Header from "@admin/components/header"
import { useContext } from "react"
import Input from "@admin/components/input"
import Button from "@admin/components/button"
import { IoMdArrowForward, IoMdCopy, IoMdDownload, IoMdOpen, IoMdSave } from "react-icons/io"
import { AssetApi } from "@admin/apis"
import { MessageContext, MessageContextType } from "@admin/store/message"

export default function Setting4() {
    const navigate = useNavigate();
    const { state, reset } = useContext(MessageContext) as MessageContextType;

    function handleNext() {
        reset();
        navigate("/message/create");
    }

    function handleOpen() {
        window.open(state.link);
    }

    function handleCopy() {
        window.navigator.clipboard.writeText(state.link);
    }

    async function handleSave() {
        var canvas = document.getElementById("canvas") as HTMLCanvasElement || null;

        if (canvas) {
            const data = canvas.toDataURL();
            const response = await AssetApi.uploadCanvas(data);
            console.log(response);
        }
    }

    function handleDownload() {
        var link = document.createElement("a");
        var canvas = document.getElementById("canvas") as HTMLCanvasElement || null;

        if (canvas && link) {
            link.setAttribute('download', 'card.png');
            link.setAttribute('href', canvas.toDataURL("image/png").replace("image/png", "image/octet-stream"));
            link.click();
        }
    }

    return (
        <div>
            <Header
                title="Xong rùi!"
                subtitle="Đây là link đến lời chúc của bạn"
            />

            <div className="pt-8 h-full">
                <Form
                    onSubmit={handleNext}
                    input_component={
                        <>
                            <Input
                                title="Link của bạn đây"
                                type="text"
                                id="link"
                                value={state.link}
                                disabled
                            />

                            <div className="mb-5 flex gap-2">
                                <Button onClick={handleOpen} icon_center={<IoMdOpen />} styleBtn="Alternative" type="button" />
                                <Button onClick={handleCopy} icon_center={<IoMdCopy />} styleBtn="Alternative" type="button" />
                                <Button onClick={handleSave} icon_center={<IoMdSave />} styleBtn="Alternative" type="button" />
                                <Button onClick={handleDownload} icon_center={<IoMdDownload />} type="button" />
                            </div>
                        </>
                    }

                    button_element={
                        <div>
                            <Button title="Hoàn thành" onClick={handleNext} icon={<IoMdArrowForward />} />
                        </div>
                    }>
                </Form>
            </div>
        </div>
    )

}
