// src/admin/components/select_image.vue
<template>
  <div class="flex flex-row overflow-x-scroll gap-4 py-5">
    <OptionImage
      v-for="item in data"
      @update:model-value="handleChange"
      :value="item.url"
      :defaultValue="defaultValue"
    />
  </div>
</template>

<script>
import OptionImage from "./option_image.vue";
export default {
  name: "SelectImage",
  components: {
    OptionImage,
  },
  props: {
    data: Array,
    defaultValue: String
  },
  methods: {
    handleChange(data) {
      this.$emit("update:model-value", data);
    },
  },
};
</script>

// src/admin/components/select_image.tsx
import OptionImage from "./option_image";

interface IProps {
  data: Array<{
    name: string,
    value: string
  }>,
  value: string,
  title: string,
  id: string,
  onChange: (data: string) => void
}

export default function SelectImage({ data, value, onChange, id, title }: IProps) {
  function handleChange(data: any) {
    onChange && onChange(data);
  }

  return (
    <div className="flex flex-col overflow-hidden">
      <label htmlFor={id} className="block mb-2 text-sm font-medium text-gray-900 flex-none">{title}</label>

      <div className="flex flex-row flex-wrap gap-4 py-5 overflow-y-scroll" id={id}>
        {data.map((item, index) => (
          <OptionImage
            name={id}
            key={index.toString()}
            onChange={handleChange}
            value={item.value}
            checked={value === item.value}
          />
        ))}
      </div>
    </div>

  )
}
